apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
   tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: web
      labels:
        app: web
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - image: yashbhuva/web:v1
        name: web
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
        livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
        resources:
           limits:
             memory: 600Mi
           requests:
             memory: 400Mi
